# RENAME FILE TO 'config.yml'
bot:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiIxMjE1NjI5MTMzNDc2OTI1MTY4IiwiaWF0IjoxNzA5ODk4OTcwfQ.96UOPowGJlrSITd3biITG_S-GkwthvX6-KVhzpkcWIc
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
