# RENAME FILE TO 'config.yml'
bot:
  token: MTIxNTYyNzQyNDcyNTk5MTQ0NQ.GxQSwP.Bcswsau3R7kpdO4jUy6xJuBDMl70OJddOGe0KM
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
